### ISSUE TITLE
feat: betterdiscord plugins through bdcompat

### ISSUE THREAD

**Issue by nouun** [LavaDesu/powercord-overlay#2]
The ability to use BetterDiscord plugins would be a nice addition as there are some plugins which Powercord is missing.

**Comment by viperML** [comment]
First, thanks @LavaDesu for the overlay, it works like a charm.

I also wanted to invesitgate if this could be possible, and thought about these two options:

- Adding a new inputs to `themes` and `plugins`, along the lines of `bdPlugins`. The behaviour should be the same to `plugins`: passing a list of derivations for each plugin. Just by having 1 or more, would also pull bd compat into `plugins`, and set the subdirectories accordingly.
- Passing as a `plugin` a derivation that has bdcompat + any BD plugins installed. Something like:
  ```nix
  discord-plugged.override {
  plugins = [
    (fetchFromGitHub { }) # powercord plugin X
    ( bdCompat.withPlugins (_: [
      (fetchFromGitHub {  }) # bd plugin Y
      (fetchFromGitHub {  }) # bd plugin Z
    ]))
  ];
};
  ```

**Comment by nouun** [comment]
Superceeded by #5
