### ISSUE TITLE
Cannot disable updater.

### ISSUE THREAD

**Issue by IQubic** [LavaDesu/powercord-overlay#3]
So, I've just installed this via the overlay, and when I try to run DiscordCanary, I'm told there's a new update, and I have drop down menu where I can select .deb, .tar.gz, or I'll figure it out. How do I disable the automatic update mechanism?

**Comment by LavaDesu** [comment]
This is Discord's built-in updater, and has nothing to do with this overlay or powercord.
I'm not aware of any methods to bypass it. You just have to wait for nixpkgs to update it, or override the src yourself temporarily to a newer version (something like this https://github.com/LavaDesu/flakes/blob/3fb3e60768061fe8d62ca298bb768ed533140aa6/overlays/discord.nix)
