### ISSUE TITLE
Workflow when developing plugins/themes?

### ISSUE THREAD

**Issue by somasis** [LavaDesu/powercord-overlay#6]
Hi there,

I'm currently working on a Powercord plugin, and I was wondering if there's a good way to add it to `pkgs.discord-plugged.override`'s `plugins` list without adding it to the Nix store. I currently have the plugin added as a non-flake input in `flake.nix` that points to my local Git repository, but in the past (on Arch Linux) I would make changes and simply refresh the client on plugin changes, as it was quicker. Is there a way I could do this, adding it to the `plugins` list as a symlink or something similar so I can develop on it without constantly having to rebuild?

Thanks for this great overlay.

**Comment by LavaDesu** [comment]
You can use [config.lib.files.mkOutOfStoreSymlink](https://github.com/nix-community/home-manager/blob/master/modules/files.nix#L64-L69) if you're using home-manager
If you're not, you can just copy-paste the lib function (it's pretty simple)

**Comment by somasis** [comment]
sorry, I should have mentioned, I'm indeed doing this in home-manager, and I tried using `mkOutOfStoreSymlink` before this issue, the problem I ran into though was this error when running `nixos-rebuild`:

```
error: access to canonical path '/home/somasis/src/powercord/discord-tokipona/manifest.json' is forbidden in restricted mode
```

This is what lead me to believe I wasn't going about it the right way with `mkOutOfStoreSymlink`.

**Comment by somasis** [comment]
Actually, running `nixos-rebuild` with `--impure` works... but that's surprising though, at least because I've used `mkOutOfStoreSymlink` some other occasions in my home-manager configuration without it complaining that it's impure...

**Comment by LavaDesu** [comment]
Ah, it's likely because the overlay accesses the manifest in the plugin to grab a friendly name for it, which makes it impure.
`--impure` is a suitable temporary workaround, since it *is* impure

**Comment by somasis** [comment]
I guess then the only real change that could happen is a way to turn off reading the manifest for a plugin, but I'm not sure looking at https://github.com/LavaDesu/powercord-overlay/blob/master/drvs/powercord.nix what the manifest is really even being used for. Though, `--impure` works for the most part I think.
