### ISSUE TITLE
Powercord no longer working

### ISSUE THREAD

**Issue by IQubic** [LavaDesu/powercord-overlay#7]
So, I'm not sure what's going on, but powercord isn't working for me anymore. Earlier today, I updated my system and now the binaries installed by your overlay are no longer working. I use a flake to install discord-plugged, and it gives me two binaries: `discordcanary` and `DiscordCanary`. I'm not sure what the difference between these two are, but both of these seem to just launch default Discord with no Powercord plugins.

My entire system config is here: https://github.com/IQubic/nixos-config
The things to take note of are this line in `flake.nix`: https://github.com/IQubic/nixos-config/blob/main/flake.nix#L45
and the entirety of `powercord.nix`: https://github.com/IQubic/nixos-config/blob/main/hm/powercord.nix

`powercord.nix` is imported by `home.nix`, which is referenced in `flake.nix`.

**Comment by LavaDesu** [comment]
Discord recently pushed changes that break powercord for everyone, can you try updating the overlay to see if it works? Just `nix flake lock --update-input powercord` should do it.

**Comment by IQubic** [comment]
Thank you. This issue is now solved for me!
